### ISSUE TITLE
[SUGGESTION]: Improve Backend Imports

### ISSUE THREAD

**Issue by dsousa12** [xgeekshq/split#331]
## Summary

With this changes we avoid:
- Imports with `../` n times;
- Organize imports;
- When run ESLint, fix the non-used imports.

### Tasks

- [x] Set `paths` on `tsconfig.json`;
- [x] Update `.eslintrc.js` config;
- [x] Install **ESLint** dependencies to fix the imports.

### Motivation

Clean the imports using `paths` from **Typescript** and improve commit actions with **ESLint** and `lint-staged`.
