### ISSUE TITLE
[REFACTOR]: Votes Structure

### ISSUE THREAD

**Issue by dsousa12** [xgeekshq/split#386]
## Summary

Currently each vote represents an entry on array containing the **User ID**, for example:

```
votes: ['user 1', 'user 2', 'user 1']
```

### Problems?
- If an user leave 20 votes in one card, the same ID appears 20 times on that array
- Another problem is you can't use a debouncer (for example) to avoid a lot of requests if the user spam the votes button. **Why?** because the request to add or remove a vote only add a new entry.

### Improvements

If we change the votes structure for something similar to this":
```ts
votes: {
	userId: string,
	votes: number
}[]
```

- We can use a debouncer to avoid the multiple requests if the user spams the vote button, changing the request to send the number of votes to add instead only incrementing the value (for example);
- No need to reference the **User ID** with **User** schema (my opinion);
- The array of votes is cleaner, because the **User ID** only appears one time.

### Motivation

Fix the problem when user spam the add/remove votes button (a lot of requests) and create a more readable structure.

### Tasks

- [ ] Change schemas
	- `card.item.schema.ts`
	- `card.schema.ts`
- [ ] Create new schemas for votes
- [ ] Create new DTOs for votes
- [ ] Change controllers and services
	- `votes.controller.ts`
	- `create.vote.service.ts`
	- `delete.vote.service.ts`
- [ ] Change the logic on frontend
- [ ] **OPTIONAL:** user debouncer and instead increment votes, receive a number of votes on `body`

**Comment by geomarb** [comment]
LGTM

**Comment by dsousa12** [comment]
> LGTM, but as we are changing from an array of userId to a more structured object, it will be better to create a schema and dto for Vote instead of using an array of objects.

Agree @geomarb
